// AUTO-GENERATED by tauri-specta. DO NOT EDIT.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Return current device info. */
	getDeviceInfo: () => __TAURI_INVOKE<DeviceInfo>("get_device_info"),
	/**
	 *  Update device name and persist to config; restart P2P node if running
	 *  so the new name propagates via libp2p Identify agent_version.
	 */
	setDeviceName: (name: string) => __TAURI_INVOKE<null>("set_device_name", { name }),
	/**  Idempotently open / create a workspace and bind it to the invoking window. */
	openWorkspace: (path: string) => __TAURI_INVOKE<WorkspaceInfo>("open_workspace", { path }),
	/**  Return info for the workspace currently bound to this window. */
	getWorkspaceInfo: () => __TAURI_INVOKE<{
	id: string,
	name: string,
	path: string,
	created_by: string,
	created_at: string,
	updated_at: string,
	/**
	 *  Number of document rows in this workspace's DB. Populated at construction
	 *  time (0) and refreshed on demand via [`WorkspaceCore::fresh_info`] — the
	 *  `info()` getter returns the last-cached snapshot without hitting the DB.
	 */
	doc_count?: number,
} | null>("get_workspace_info"),
	getRecentWorkspaces: () => __TAURI_INVOKE<RecentWorkspace[]>("get_recent_workspaces"),
	/**  Open a workspace window: reuse existing / bind to caller / create new. */
	openWorkspaceWindow: (path: string, bindToWindow: string | null, closeWindow: string | null) => __TAURI_INVOKE<OpenWorkspaceWindowResult>("open_workspace_window", { path, bindToWindow, closeWindow }),
	finishOnboarding: () => __TAURI_INVOKE<null>("finish_onboarding"),
	removeRecentWorkspace: (path: string) => __TAURI_INVOKE<null>("remove_recent_workspace", { path }),
	openWorkspaceManagerWindow: () => __TAURI_INVOKE<null>("open_workspace_manager_window"),
	openSettingsWindow: (route: string | null) => __TAURI_INVOKE<null>("open_settings_window", { route }),
	/**  Create a workspace for sync (no window, pre-assigned UUID). */
	createWorkspaceForSync: (uuid: string, name: string, basePath: string) => __TAURI_INVOKE<string>("create_workspace_for_sync", { uuid, name, basePath }),
	dbUpsertDocument: (input: UpsertDocumentInput) => __TAURI_INVOKE<null>("db_upsert_document", { input }),
	deleteDocumentByRelPath: (relPath: string) => __TAURI_INVOKE<null>("delete_document_by_rel_path", { relPath }),
	deleteDocumentsByPrefix: (prefix: string) => __TAURI_INVOKE<number>("delete_documents_by_prefix", { prefix }),
	renameDocument: (input: RenameDocumentInput) => __TAURI_INVOKE<null>("rename_document", { input }),
	/**
	 *  Atomically move a document or folder.
	 * 
	 *  Uses [`swarmnote_core::fs::ops::move_node`] for the physical move, then
	 *  rebases DB rows + in-memory YDocManager entries accordingly.
	 */
	moveDocument: (input: MoveDocumentInput) => __TAURI_INVOKE<MoveDocumentResult>("move_document", { input }),
	dbGetFolders: (workspaceId: string) => __TAURI_INVOKE<FolderRow[]>("db_get_folders", { workspaceId }),
	dbCreateFolder: (input: CreateFolderInput) => __TAURI_INVOKE<FolderRow>("db_create_folder", { input }),
	dbDeleteFolder: (id: string) => __TAURI_INVOKE<null>("db_delete_folder", { id }),
	scanWorkspaceTree: () => __TAURI_INVOKE<FileTreeNode_Serialize[]>("scan_workspace_tree"),
	fsCreateFile: (parentRel: string, name: string) => __TAURI_INVOKE<string>("fs_create_file", { parentRel, name }),
	fsCreateDir: (parentRel: string, name: string) => __TAURI_INVOKE<string>("fs_create_dir", { parentRel, name }),
	fsDeleteFile: (relPath: string) => __TAURI_INVOKE<null>("fs_delete_file", { relPath }),
	fsDeleteDir: (relPath: string) => __TAURI_INVOKE<null>("fs_delete_dir", { relPath }),
	fsRename: (relPath: string, newName: string) => __TAURI_INVOKE<string>("fs_rename", { relPath, newName }),
	loadDocument: (relPath: string) => __TAURI_INVOKE<string>("load_document", { relPath }),
	saveDocument: (relPath: string, content: string) => __TAURI_INVOKE<SaveDocumentResult>("save_document", { relPath, content }),
	saveMedia: (relPath: string, fileName: string, data: number[]) => __TAURI_INVOKE<string>("save_media", { relPath, fileName, data }),
	/**  启动 P2P 节点。 */
	startP2pNode: () => __TAURI_INVOKE<null>("start_p2p_node"),
	/**  停止 P2P 节点。 */
	stopP2pNode: () => __TAURI_INVOKE<null>("stop_p2p_node"),
	/**  查询 P2P 节点当前运行状态。 */
	getNetworkStatus: () => __TAURI_INVOKE<NodeStatus>("get_network_status"),
	/**  获取已连接的设备列表。 */
	getConnectedPeers: () => __TAURI_INVOKE<Device[]>("get_connected_peers"),
	generatePairingCode: (expiresInSecs: number | null) => __TAURI_INVOKE<PairingCodeInfo>("generate_pairing_code", { expiresInSecs }),
	getDeviceByCode: (code: string) => __TAURI_INVOKE<DeviceByCodeResult>("get_device_by_code", { code }),
	requestPairing: (peerId: string, method: PairingMethod, remoteOsInfo: {
	/**  User-set device name, propagated via the `agent_version` `name=` field. */
	name: string | null,
	hostname: string,
	os: string,
	platform: string,
	arch: string,
} | null) => __TAURI_INVOKE<PairingResponse>("request_pairing", { peerId, method, remoteOsInfo }),
	respondPairingRequest: (pendingId: number, accept: boolean) => __TAURI_INVOKE<null>("respond_pairing_request", { pendingId, accept }),
	getPairedDevices: () => __TAURI_INVOKE<PairedDeviceInfo_Serialize[]>("get_paired_devices"),
	unpairDevice: (peerId: string) => __TAURI_INVOKE<null>("unpair_device", { peerId }),
	getNearbyDevices: () => __TAURI_INVOKE<Device[]>("get_nearby_devices"),
	listDevices: (filter: "all" | "connected" | "paired" | null) => __TAURI_INVOKE<DeviceListResult>("list_devices", { filter }),
	/**  并发查询所有已配对在线 peer 的工作区列表，标记 is_local。 */
	getRemoteWorkspaces: () => __TAURI_INVOKE<RemoteWorkspaceInfo[]>("get_remote_workspaces"),
	openYdoc: (relPath: string, workspaceId: string) => __TAURI_INVOKE<OpenDocResult>("open_ydoc", { relPath, workspaceId }),
	applyYdocUpdate: (docUuid: string, update: number[]) => __TAURI_INVOKE<null>("apply_ydoc_update", { docUuid, update }),
	broadcastAwareness: (docUuid: string, update: number[]) => __TAURI_INVOKE<null>("broadcast_awareness", { docUuid, update }),
	closeYdoc: (docUuid: string) => __TAURI_INVOKE<null>("close_ydoc", { docUuid }),
	renameYdoc: (docUuid: string, newRelPath: string) => __TAURI_INVOKE<null>("rename_ydoc", { docUuid, newRelPath }),
	reloadYdocConfirmed: (docUuid: string) => __TAURI_INVOKE<null>("reload_ydoc_confirmed", { docUuid }),
	hydrateWorkspace: (workspaceUuid: string, onProgress: Channel<HydrateProgress>) => __TAURI_INVOKE<HydrateResult>("hydrate_workspace", { workspaceUuid, onProgress }),
	triggerWorkspaceSync: (workspaceUuid: string, peerId: string) => __TAURI_INVOKE<null>("trigger_workspace_sync", { workspaceUuid, peerId }),
	/**  Grant a paired device Collaborator access to the workspace (owner only). */
	shareWorkspaceToDevice: (workspaceUuid: string, targetPeerId: string) => __TAURI_INVOKE<null>("share_workspace_to_device", { workspaceUuid, targetPeerId }),
	/**  List the workspace's current members (role + device presence). */
	listWorkspaceMembers: (workspaceUuid: string) => __TAURI_INVOKE<MemberInfo[]>("list_workspace_members", { workspaceUuid }),
	/**  Revoke a member's access (owner only). */
	revokeWorkspaceMember: (workspaceUuid: string, targetPeerId: string) => __TAURI_INVOKE<null>("revoke_workspace_member", { workspaceUuid, targetPeerId }),
};

/** Events */
export const events = {
	devicesChanged: makeEvent<DevicesChanged>("devices-changed"),
	docFlushed: makeEvent<DocFlushed>("doc-flushed"),
	externalAwarenessUpdate: makeEvent<ExternalAwarenessUpdate>("external-awareness-update"),
	externalConflict: makeEvent<ExternalConflict>("external-conflict"),
	externalUpdate: makeEvent<ExternalUpdate>("external-update"),
	fileTreeChanged: makeEvent<FileTreeChanged>("file-tree-changed"),
	navigate: makeEvent<Navigate>("navigate"),
	networkStatusChanged: makeEvent<NetworkStatusChanged>("network-status-changed"),
	nodeStarted: makeEvent<NodeStarted>("node-started"),
	nodeStopped: makeEvent<NodeStopped>("node-stopped"),
	pairedDeviceAdded: makeEvent<PairedDeviceAdded_Deserialize>("paired-device-added"),
	pairedDeviceRemoved: makeEvent<PairedDeviceRemoved>("paired-device-removed"),
	pairingRequestReceived: makeEvent<PairingRequestReceived>("pairing-request-received"),
	syncCompleted: makeEvent<SyncCompleted>("sync-completed"),
	syncProgress: makeEvent<SyncProgress>("sync-progress"),
	syncStarted: makeEvent<SyncStarted>("sync-started"),
	workspaceReady: makeEvent<WorkspaceReady>("workspace-ready"),
};

/* Types */
/**  连接类型 */
export type ConnectionType = "lan" | "dcutr" | "relay";

/**  Input for [`DocumentCrud::create_folder`]. */
export type CreateFolderInput = {
	workspace_id: string,
	parent_folder_id: string | null,
	name: string,
	rel_path: string,
};

/**  统一的设备输出类型（发送给前端） */
export type Device = {
	peerId: string,
	name: string | null,
	hostname: string,
	os: string,
	platform: string,
	arch: string,
	status: DeviceStatus,
	connection: ConnectionType | null,
	latency: number | null,
	isPaired: boolean,
	pairedAt: string | null,
	lastSeen: string | null,
};

/**  `get_device_by_code` 的类型化返回值。 */
export type DeviceByCodeResult = {
	peerId: string,
	osInfo: OsInfo,
};

/**  设备过滤器 */
export type DeviceFilter = "all" | "connected" | "paired";

/**
 *  Runtime device identity + OS metadata. Returned to the frontend by
 *  `get_device_info`.
 */
export type DeviceInfo = {
	peer_id: string,
	device_name: string,
	hostname: string,
	os: string,
	platform: string,
	arch: string,
	created_at: string,
};

/**  设备列表查询结果 */
export type DeviceListResult = {
	devices: Device[],
	total: number,
};

/**  设备状态 */
export type DeviceStatus = "online" | "offline";

export type DevicesChanged = Device[];

export type DocFlushed = {
	docUuid: string,
};

export type ExternalAwarenessUpdate = {
	docUuid: string,
	update: number[],
};

export type ExternalConflict = {
	docUuid: string,
	relPath: string,
};

export type ExternalUpdate = {
	docUuid: string,
	update: number[],
};

export type FileTreeChanged = {
	workspaceId: string,
};

/**
 *  A node in the workspace file tree returned by [`FileSystem::scan_tree`].
 * 
 *  Matches the shape emitted to the frontend — do not change field names
 *  without coordinating with `src/commands/fs.ts` and the file-tree store.
 */
export type FileTreeNode = FileTreeNode_Serialize | FileTreeNode_Deserialize;

/**
 *  A node in the workspace file tree returned by [`FileSystem::scan_tree`].
 * 
 *  Matches the shape emitted to the frontend — do not change field names
 *  without coordinating with `src/commands/fs.ts` and the file-tree store.
 */
export type FileTreeNode_Deserialize = {
	/**  Workspace-relative path (stable ID in the frontend tree). */
	id: string,
	/**  Display name. For `.md` files the extension is stripped. */
	name: string,
	/**  `Some(children)` for directories, `None` for files. */
	children: FileTreeNode_Deserialize[] | null,
};

/**
 *  A node in the workspace file tree returned by [`FileSystem::scan_tree`].
 * 
 *  Matches the shape emitted to the frontend — do not change field names
 *  without coordinating with `src/commands/fs.ts` and the file-tree store.
 */
export type FileTreeNode_Serialize = {
	/**  Workspace-relative path (stable ID in the frontend tree). */
	id: string,
	/**  Display name. For `.md` files the extension is stripped. */
	name: string,
	/**  `Some(children)` for directories, `None` for files. */
	children?: FileTreeNode_Serialize[] | null,
};

/**
 *  文件夹行 —— `db_create_folder` / `db_get_folders` 的 IPC 返回类型。
 * 
 *  `entity::folders::Model` 的 struct 名硬编码为 `Model`,与 `documents::Model`
 *  撞名后会在 TS bindings 里冲突。这里定义投影 DTO 解耦 sea-orm relation 字段。
 */
export type FolderRow = {
	id: string,
	workspaceId: string,
	parentFolderId: string | null,
	name: string,
	relPath: string,
	createdBy: string,
	createdAt: string,
	updatedAt: string,
};

/**  Progress tick emitted during hydration. */
export type HydrateProgress = {
	current: number,
	total: number,
};

/**  Summary returned when hydration completes. */
export type HydrateResult = {
	generated: number,
	merged: number,
	skipped: number,
	failed: number,
};

/**
 *  A workspace member (materialized role + device presence), for the
 *  member-management UI.
 */
export type MemberInfo = {
	peerId: string,
	role: Role,
	name: string | null,
	os: string,
	isOnline: boolean,
	/**  `true` for this device's own row (the owner) — UI hides revoke/role edit. */
	isSelf: boolean,
};

export type MoveDocumentInput = {
	/**  源路径（文件或目录），相对工作区根。 */
	fromRelPath: string,
	/**  目标完整路径（不是目标父目录），相对工作区根。 */
	toRelPath: string,
};

export type MoveDocumentResult = {
	newRelPath: string,
	isDir: boolean,
};

/**
 *  设置窗口的路由切换信号 —— 用户再次点击设置入口时,把已经存在的设置窗口
 *  切到指定 sub-route(general/sync/devices/about 等)。payload 是目标路径。
 */
export type Navigate = string;

export type NetworkStatusChanged = {
	natStatus: string,
	publicAddr: string | null,
};

export type NodeStarted = null;

/**  P2P 节点状态——Rust/前端共用的 single source of truth。 */
export type NodeStatus = { kind: "stopped" } | { kind: "running" } | { kind: "error"; message: string };

export type NodeStopped = null;

/**  Returned by [`YDocManager::open_doc`] so the frontend knows the stable UUID. */
export type OpenDocResult = {
	/**  Stable document UUID (database primary key). */
	doc_uuid: string,
	/**  Full Y.Doc state as binary v1 update. */
	yjs_state: number[],
};

export type OpenWorkspaceWindowResult = { kind: "bound_to_caller"; info: WorkspaceInfo } | { kind: "focused_existing" } | { kind: "new_window" };

/**
 *  Device operating system + user-facing name, embedded in the
 *  `agent_version` string libp2p advertises via Identify.
 */
export type OsInfo = {
	/**  User-set device name, propagated via the `agent_version` `name=` field. */
	name: string | null,
	hostname: string,
	os: string,
	platform: string,
	arch: string,
};

/**
 *  已配对设备新增。`Option`:出站配对响应不回带 peer info(收方填),前端
 *  接到 `None` 仅作为"刷新设备列表"信号。
 */
export type PairedDeviceAdded = PairedDeviceAdded_Serialize | PairedDeviceAdded_Deserialize;

/**
 *  已配对设备新增。`Option`:出站配对响应不回带 peer info(收方填),前端
 *  接到 `None` 仅作为"刷新设备列表"信号。
 */
export type PairedDeviceAdded_Deserialize = PairedDeviceInfo_Deserialize | null;

/**
 *  已配对设备新增。`Option`:出站配对响应不回带 peer info(收方填),前端
 *  接到 `None` 仅作为"刷新设备列表"信号。
 */
export type PairedDeviceAdded_Serialize = PairedDeviceInfo_Serialize | null;

/**  已配对设备信息，同时用于运行时缓存和 Tauri Event payload。 */
export type PairedDeviceInfo = PairedDeviceInfo_Serialize | PairedDeviceInfo_Deserialize;

/**  已配对设备信息，同时用于运行时缓存和 Tauri Event payload。 */
export type PairedDeviceInfo_Deserialize = {
	peerId: string,
	name: string | null,
	hostname: string,
	os: string,
	platform: string,
	arch: string,
	pairedAt: string,
	lastSeen: string | null,
	isOnline: boolean | null,
	rttMs: number | null,
};

/**  已配对设备信息，同时用于运行时缓存和 Tauri Event payload。 */
export type PairedDeviceInfo_Serialize = {
	peerId: string,
	name?: string | null,
	hostname: string,
	os: string,
	platform: string,
	arch: string,
	pairedAt: string,
	lastSeen: string | null,
	isOnline?: boolean | null,
	rttMs?: number | null,
};

export type PairedDeviceRemoved = {
	peerId: string,
};

/**  配对码信息，包含生成的 6 位数字码及其有效期。 */
export type PairingCodeInfo = {
	code: string,
	createdAt: string,
	expiresAt: string,
};

export type PairingMethod = { type: "Code"; code: string } | { type: "Direct" };

export type PairingRefuseReason = "UserRejected" | "CodeExpired" | "CodeInvalid";

export type PairingRequestReceived = {
	pendingId: number,
	peerId: string,
	osInfo: OsInfo,
	method: PairingMethod,
	expiresAt: string,
};

export type PairingResponse = { status: "Success" } | { status: "Refused"; reason: PairingRefuseReason };

export type RecentWorkspace = {
	path: string,
	name: string,
	last_opened_at: string,
	/**  Workspace UUID, used by the frontend to match live sync state. */
	uuid?: string | null,
};

/**  远程工作区信息（合并来源 peer 信息） */
export type RemoteWorkspaceInfo = {
	uuid: string,
	name: string,
	docCount: number,
	updatedAt: number,
	peerId: string,
	peerName: string,
	isLocal: boolean,
};

export type RenameDocumentInput = {
	oldRelPath: string,
	newRelPath: string,
	newTitle: string,
};

/**  Workspace role. v1 two-tier; `Reader` is reserved for v2. */
export type Role = "owner" | "collaborator";

export type SaveDocumentResult = {
	/**  blake3 hash hex string */
	fileHash: string,
};

export type SyncCompleted = {
	workspaceUuid: string,
	peerId: string,
	result: SyncResult,
	error: string | null,
};

export type SyncProgress = {
	workspaceUuid: string,
	peerId: string,
	completed: number,
	total: number,
};

export type SyncResult = "success" | "error" | "cancelled";

export type SyncStarted = {
	workspaceUuid: string,
	peerId: string,
};

/**
 *  Input for [`DocumentCrud::upsert_document`]. Preserves the Tauri IPC wire
 *  shape (see `src/commands/document.ts`).
 */
export type UpsertDocumentInput = {
	id: string | null,
	workspace_id: string,
	folder_id: string | null,
	title: string,
	rel_path: string,
	file_hash: string | null,
};

/**
 *  Runtime + DB record of an open workspace. Returned to the frontend by
 *  `get_workspace_info`-style commands; held by [`WorkspaceCore`] as its
 *  own metadata snapshot.
 */
export type WorkspaceInfo = {
	id: string,
	name: string,
	path: string,
	created_by: string,
	created_at: string,
	updated_at: string,
	/**
	 *  Number of document rows in this workspace's DB. Populated at construction
	 *  time (0) and refreshed on demand via [`WorkspaceCore::fresh_info`] — the
	 *  `info()` getter returns the last-cached snapshot without hitting the DB.
	 */
	doc_count?: number,
};

/**
 *  工作区绑定到调用方窗口后的回调 payload。`open_workspace_window` 命令在创建
 *  新窗口或绑定到 caller 时,通过 `WebviewWindow::emit("workspace-ready", ...)`
 *  发送,前端用 `events.workspaceReady.listen()` 接收。
 */
export type WorkspaceReady = WorkspaceInfo;

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

