//! 强制 export TypeScript bindings 的测试。
//!
//! 直接跑 `cargo build` 时 `setup::specta_builder()` 中的 `export` 不会被触发
//! (因为 `tauri::Builder.run()` 没起来)。把 export 抽到 `cargo test` 里就能
//! 在不启动应用的情况下,直接产出最新的 `src/lib/bindings.ts`,方便 CI 和本
//! 地开发流程:
//!
//! ```bash
//! cargo test -p swarmnote --test specta_export -- --nocapture
//! ```

use specta_typescript::Typescript;

#[test]
fn export_bindings() {
    let builder = swarmnote_lib::specta_builder();
    builder
        .export(
            Typescript::default().header("// AUTO-GENERATED by tauri-specta. DO NOT EDIT.\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export specta TypeScript bindings");
}
